#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────
# Extracts the Ed25519 public key from .local/signing.key
# and writes DemoConfig.generated.swift with the key bytes.
# ──────────────────────────────────────────────────────────
set -euo pipefail

DEMO_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$DEMO_DIR/../../.." && pwd)"
KEY_FILE="$REPO_ROOT/.local/signing.key"
OUTPUT="$DEMO_DIR/AirStringsDemo/DemoConfig.generated.swift"

if [ ! -f "$KEY_FILE" ]; then
  echo "ERROR: Signing key not found at $KEY_FILE"
  echo "Run 'bash backend/scripts/smoke-run.sh' from the repo root first."
  exit 1
fi

# Ed25519 private key is 64 bytes: 32-byte seed + 32-byte public key
# Extract the last 32 bytes (public key)
PUBLIC_KEY_HEX=$(tail -c 32 "$KEY_FILE" | xxd -p -c 32)

if [ ${#PUBLIC_KEY_HEX} -ne 64 ]; then
  echo "ERROR: Expected 32-byte public key (64 hex chars), got ${#PUBLIC_KEY_HEX}"
  exit 1
fi

# Convert hex to Swift Data literal: 0xAA, 0xBB, ...
SWIFT_BYTES=""
for ((i = 0; i < ${#PUBLIC_KEY_HEX}; i += 2)); do
  BYTE="${PUBLIC_KEY_HEX:$i:2}"
  if [ -n "$SWIFT_BYTES" ]; then
    SWIFT_BYTES+=", "
  fi
  SWIFT_BYTES+="0x${BYTE}"
done

cat > "$OUTPUT" << EOF
// Auto-generated by generate-config.sh — DO NOT EDIT
// Public key extracted from .local/signing.key
import Foundation

extension DemoConfig {
    static let publicKeyData = Data([${SWIFT_BYTES}])
}
EOF

echo "Generated $OUTPUT"
echo "  Public key: ${PUBLIC_KEY_HEX}"
